import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import ContextProvider from "./context/context-wrapper";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ContextProvider>
            <Navbar />

            <main className="w-full h-full halftone pt-16">{children}</main>
          </ContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
