import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import ContextProvider from "./context/context-wrapper";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <main className="w-full h-full halftone">
            <Navbar />
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
